version: "3.8"

x-shared-limit:
    &mem_limit
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

x-shared:
    &neo4j-common
    NEO4J_AUTH: neo4j/1234
    NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    NEO4J_causal__clustering_initial__discovery__members: neo4jcore1:5000,neo4jcore2:5000,neo4jcore3:5000
    NEO4J_dbms_memory_pagecache_size: "100M" 
    NEO4J_dbms_memory_heap_initial__size: "100M"
    NEO4J_dbms_security_procedures_unrestricted: apoc.*,algo.*
    NEO4J_dbms_security_procedures_allowlist: apoc.*,algo.*
    NEO4JLABS_PLUGINS: '["apoc"]'

x-shared-core:
    &neo4j-common-core
    <<: *neo4j-common
    NEO4J_dbms_mode: CORE
    NEO4J_causal__clustering_minimum__core__cluster__size__at__formation: 3

networks: 
    lan:

services:
    
    webapi:
        build: ./WebAPI
        <<: *mem_limit
        networks:
            - lan
        ports: 
            - 8000:80

    neo4jcore1:
        image: neo4j:4.2-enterprise
        <<: *mem_limit
        networks:
            - lan 
        ports: 
            - "7474:7474"
            - "7687:7687"
        environment:
            <<: *neo4j-common-core
            NEO4J_causal__clustering_discovery__advertised__address: neo4jcore1:5000 
            NEO4J_causal__clustering_transaction__advertised__address: neo4jcore1:6000 
            NEO4J_causal__clustering_raft__advertised__address: neo4jcore1:7000
            NEO4J_dbms_default__advertised__address: neo4jcore1
            NEO4J_dbms_connector_http_listen__address: :7474
            NEO4J_dbms_connector_bolt_listen__address: :7687
        healthcheck:
            test: wget http://localhost:7474/browser -O -
            interval: 2s
            timeout: 5s
            retries: 40

    neo4jcore2:
        image: neo4j:4.2-enterprise
        <<: *mem_limit
        networks:
            - lan
        ports:
            - "7475:7475"
            - "7688:7688"
        environment:
            <<:  *neo4j-common-core
            NEO4J_causal__clustering_discovery__advertised__address: neo4jcore2:5000
            NEO4J_causal__clustering_transaction__advertised__address: neo4jcore2:6000
            NEO4J_causal__clustering_raft__advertised__address: neo4jcore2:7000
            NEO4J_dbms_default__advertised__address: neo4jcore2
            NEO4J_dbms_connector_http_listen__address: :7475
            NEO4J_dbms_connector_bolt_listen__address: :7688
        healthcheck:
            test: wget http://localhost:7475/browser -O -
            interval: 2s
            timeout: 5s
            retries: 40

    neo4jcore3:
        image: neo4j:4.2-enterprise
        <<: *mem_limit
        networks:
            - lan
        ports:
            - "7476:7476"
            - "7689:7689"
        environment:
            <<:  *neo4j-common-core
            NEO4J_causal__clustering_discovery__advertised__address: neo4jcore3:5000
            NEO4J_causal__clustering_transaction__advertised__address: neo4jcore3:6000
            NEO4J_causal__clustering_raft__advertised__address: neo4jcore3:7000
            NEO4J_dbms_default__advertised__address: neo4jcore3
            NEO4J_dbms_connector_http_listen__address: :7476
            NEO4J_dbms_connector_bolt_listen__address: :7689
        healthcheck:
            test: wget http://localhost:7476/browser -O -
            interval: 2s
            timeout: 5s
            retries: 40

    neo4jreadreplica1:
        image: neo4j:4.2-enterprise
        <<: *mem_limit
        networks:
            - lan
        ports:
            - "7477:7477"
            - "7690:7690"
        environment:
            <<:  *neo4j-common
            NEO4J_dbms_mode: READ_REPLICA
            NEO4J_causal__clustering_discovery__advertised__address: neo4jreadreplica1:5000
            NEO4J_causal__clustering_transaction__advertised__address: neo4jreadreplica1:6000
            NEO4J_causal__clustering_raft__advertised__address: neo4jreadreplica1:7000
            NEO4J_dbms_default__advertised__address: neo4jreadreplica1
            NEO4J_dbms_connector_http_listen__address: :7477
            NEO4J_dbms_connector_bolt_listen__address: :7690
        healthcheck:
            test: wget http://localhost:7477/browser -O -
            interval: 2s
            timeout: 5s
            retries: 40

    neo4jreadreplica2:
        image: neo4j:4.2-enterprise
        <<: *mem_limit
        networks:
            - lan
        ports:
            - "7478:7478"
            - "7691:7691"
        environment:
            <<:  *neo4j-common
            NEO4J_dbms_mode: READ_REPLICA
            NEO4J_causal__clustering_discovery__advertised__address: neo4jreadreplica2:5000
            NEO4J_causal__clustering_transaction__advertised__address: neo4jreadreplica2:6000
            NEO4J_causal__clustering_raft__advertised__address: neo4jreadreplica2:7000
            NEO4J_dbms_default__advertised__address: neo4jreadreplica2
            NEO4J_dbms_connector_http_listen__address: :7478
            NEO4J_dbms_connector_bolt_listen__address: :7691
        healthcheck:
            test: wget http://localhost:7478/browser -O -
            interval: 2s
            timeout: 5s
            retries: 40

    redis:
        image: redis:6.2.3
        <<: *mem_limit
        networks:
            - lan
        command: redis-server --requirepass 1234
        ports:
            - "6379:6379"
        environment:
            - REDIS_REPLICATION_MODE=master
        healthcheck:
            test: redis-cli -a 1234 ping
            interval: 2s
            timeout: 5s
            retries: 40

    postgres:
        image: postgres:13.3
        <<: *mem_limit
        networks:
            - lan
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
        volumes:
            - ./db_scripts/Postgres.sql:/docker-entrypoint-initdb.d/Postgres.sql
        healthcheck:
            test: pg_isready -U postgres
            interval: 2s
            timeout: 5s
            retries: 40

    hbasemaster:
        image: blueskyareahm/hbase-base:2.1.3
        <<: *mem_limit
        networks:
            - lan
        command: master
        ports:
            - 16000:16000
            - 16010:16010

    hbaseregionserver:
        image: blueskyareahm/hbase-base:2.1.3
        <<: *mem_limit
        networks:
            - lan
        command: regionserver
        ports:
            - 16030:16030
            - 16201:16201
            - 16301:16301

    hbaserest:
        image: blueskyareahm/hbase-base:2.1.3
        <<: *mem_limit
        networks:
            - lan
        command: rest
        ports:
            - 17005:8080

    zookeeper:
        image: blueskyareahm/hbase-zookeeper:3.4.13
        <<: *mem_limit
        networks:
            - lan
        ports:
            - 2181:2181