--
-- PostgreSQL database dump
--

-- Dumped from database version 13.1 (Debian 13.1-1.pgdg100+1)
-- Dumped by pg_dump version 13.1

-- Started on 2021-03-10 17:00:15 UTC

DROP DATABASE IF EXISTS "RelationalDatabasesExercise";
--
-- TOC entry 3002 (class 1262 OID 16624)
-- Name: RelationalDatabasesExercise; Type: DATABASE; Schema: -; Owner: softdb
--

CREATE DATABASE "RelationalDatabasesExercise" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE "RelationalDatabasesExercise" OWNER TO softdb;

\connect "RelationalDatabasesExercise"

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 211 (class 1259 OID 16701)
-- Name: CaretakerPet; Type: TABLE; Schema: public; Owner: softdb
--

CREATE TABLE public."CaretakerPet" (
    "caretakersId" bigint NOT NULL,
    "petsId" bigint NOT NULL
);


ALTER TABLE public."CaretakerPet" OWNER TO softdb;

--
-- TOC entry 200 (class 1259 OID 16625)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: softdb
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO softdb;

--
-- TOC entry 204 (class 1259 OID 16642)
-- Name: addresses; Type: TABLE; Schema: public; Owner: softdb
--

CREATE TABLE public.addresses (
    "Id" bigint NOT NULL,
    street text,
    housenumber text,
    "cityId" bigint
);


ALTER TABLE public.addresses OWNER TO softdb;

--
-- TOC entry 203 (class 1259 OID 16640)
-- Name: addresses_Id_seq; Type: SEQUENCE; Schema: public; Owner: softdb
--

ALTER TABLE public.addresses ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."addresses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 16658)
-- Name: caretakers; Type: TABLE; Schema: public; Owner: softdb
--

CREATE TABLE public.caretakers (
    "Id" bigint NOT NULL,
    name text,
    phone text,
    "addressId" bigint
);


ALTER TABLE public.caretakers OWNER TO softdb;

--
-- TOC entry 205 (class 1259 OID 16656)
-- Name: caretakers_Id_seq; Type: SEQUENCE; Schema: public; Owner: softdb
--

ALTER TABLE public.caretakers ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."caretakers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 16632)
-- Name: cities; Type: TABLE; Schema: public; Owner: softdb
--

CREATE TABLE public.cities (
    "Id" bigint NOT NULL,
    zip text,
    city text
);


ALTER TABLE public.cities OWNER TO softdb;

--
-- TOC entry 201 (class 1259 OID 16630)
-- Name: cities_Id_seq; Type: SEQUENCE; Schema: public; Owner: softdb
--

ALTER TABLE public.cities ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."cities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 16688)
-- Name: pets; Type: TABLE; Schema: public; Owner: softdb
--

CREATE TABLE public.pets (
    "Id" bigint NOT NULL,
    name text,
    age integer NOT NULL,
    "vetId" bigint,
    "Discriminator" text NOT NULL,
    "lifeCount" integer,
    "barkPitch" text
);


ALTER TABLE public.pets OWNER TO softdb;

--
-- TOC entry 209 (class 1259 OID 16686)
-- Name: pets_Id_seq; Type: SEQUENCE; Schema: public; Owner: softdb
--

ALTER TABLE public.pets ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."pets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 16673)
-- Name: vets; Type: TABLE; Schema: public; Owner: softdb
--

CREATE TABLE public.vets (
    "Id" bigint NOT NULL,
    cvr text DEFAULT ''::text NOT NULL,
    name text,
    phone text,
    "addressId" bigint
);


ALTER TABLE public.vets OWNER TO softdb;

--
-- TOC entry 207 (class 1259 OID 16671)
-- Name: vets_Id_seq; Type: SEQUENCE; Schema: public; Owner: softdb
--

ALTER TABLE public.vets ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."vets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2860 (class 2606 OID 16705)
-- Name: CaretakerPet PK_CaretakerPet; Type: CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public."CaretakerPet"
    ADD CONSTRAINT "PK_CaretakerPet" PRIMARY KEY ("caretakersId", "petsId");


--
-- TOC entry 2842 (class 2606 OID 16629)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 2847 (class 2606 OID 16649)
-- Name: addresses PK_addresses; Type: CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT "PK_addresses" PRIMARY KEY ("Id");


--
-- TOC entry 2850 (class 2606 OID 16665)
-- Name: caretakers PK_caretakers; Type: CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public.caretakers
    ADD CONSTRAINT "PK_caretakers" PRIMARY KEY ("Id");


--
-- TOC entry 2844 (class 2606 OID 16639)
-- Name: cities PK_cities; Type: CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT "PK_cities" PRIMARY KEY ("Id");


--
-- TOC entry 2857 (class 2606 OID 16695)
-- Name: pets PK_pets; Type: CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public.pets
    ADD CONSTRAINT "PK_pets" PRIMARY KEY ("Id");


--
-- TOC entry 2854 (class 2606 OID 16680)
-- Name: vets PK_vets; Type: CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public.vets
    ADD CONSTRAINT "PK_vets" PRIMARY KEY ("Id");


--
-- TOC entry 2858 (class 1259 OID 16716)
-- Name: IX_CaretakerPet_petsId; Type: INDEX; Schema: public; Owner: softdb
--

CREATE INDEX "IX_CaretakerPet_petsId" ON public."CaretakerPet" USING btree ("petsId");


--
-- TOC entry 2845 (class 1259 OID 16655)
-- Name: IX_addresses_cityId; Type: INDEX; Schema: public; Owner: softdb
--

CREATE INDEX "IX_addresses_cityId" ON public.addresses USING btree ("cityId");


--
-- TOC entry 2848 (class 1259 OID 16717)
-- Name: IX_caretakers_addressId; Type: INDEX; Schema: public; Owner: softdb
--

CREATE INDEX "IX_caretakers_addressId" ON public.caretakers USING btree ("addressId");


--
-- TOC entry 2855 (class 1259 OID 16718)
-- Name: IX_pets_vetId; Type: INDEX; Schema: public; Owner: softdb
--

CREATE INDEX "IX_pets_vetId" ON public.pets USING btree ("vetId");


--
-- TOC entry 2851 (class 1259 OID 16719)
-- Name: IX_vets_addressId; Type: INDEX; Schema: public; Owner: softdb
--

CREATE INDEX "IX_vets_addressId" ON public.vets USING btree ("addressId");


--
-- TOC entry 2852 (class 1259 OID 16721)
-- Name: IX_vets_cvr; Type: INDEX; Schema: public; Owner: softdb
--

CREATE UNIQUE INDEX "IX_vets_cvr" ON public.vets USING btree (cvr);


--
-- TOC entry 2865 (class 2606 OID 16706)
-- Name: CaretakerPet FK_CaretakerPet_caretakers_caretakersId; Type: FK CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public."CaretakerPet"
    ADD CONSTRAINT "FK_CaretakerPet_caretakers_caretakersId" FOREIGN KEY ("caretakersId") REFERENCES public.caretakers("Id") ON DELETE CASCADE;


--
-- TOC entry 2866 (class 2606 OID 16711)
-- Name: CaretakerPet FK_CaretakerPet_pets_petsId; Type: FK CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public."CaretakerPet"
    ADD CONSTRAINT "FK_CaretakerPet_pets_petsId" FOREIGN KEY ("petsId") REFERENCES public.pets("Id") ON DELETE CASCADE;


--
-- TOC entry 2861 (class 2606 OID 16650)
-- Name: addresses FK_addresses_cities_cityId; Type: FK CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT "FK_addresses_cities_cityId" FOREIGN KEY ("cityId") REFERENCES public.cities("Id") ON DELETE RESTRICT;


--
-- TOC entry 2862 (class 2606 OID 16666)
-- Name: caretakers FK_caretakers_addresses_addressId; Type: FK CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public.caretakers
    ADD CONSTRAINT "FK_caretakers_addresses_addressId" FOREIGN KEY ("addressId") REFERENCES public.addresses("Id") ON DELETE RESTRICT;


--
-- TOC entry 2864 (class 2606 OID 16696)
-- Name: pets FK_pets_vets_vetId; Type: FK CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public.pets
    ADD CONSTRAINT "FK_pets_vets_vetId" FOREIGN KEY ("vetId") REFERENCES public.vets("Id") ON DELETE RESTRICT;


--
-- TOC entry 2863 (class 2606 OID 16681)
-- Name: vets FK_vets_addresses_addressId; Type: FK CONSTRAINT; Schema: public; Owner: softdb
--

ALTER TABLE ONLY public.vets
    ADD CONSTRAINT "FK_vets_addresses_addressId" FOREIGN KEY ("addressId") REFERENCES public.addresses("Id") ON DELETE RESTRICT;


-- Completed on 2021-03-10 17:00:15 UTC

--
-- PostgreSQL database dump complete
--

